import type { Citation, RagDocument } from '../types'

const uid = () => Math.random().toString(36).slice(2, 10)

// In-memory document store, seeded with a few examples. Persists for the
// lifetime of the page (resets on reload) — stand-in for the backend.
export const documents: RagDocument[] = [
  {
    id: uid(),
    name: 'Employee Handbook 2026.pdf',
    sizeBytes: 1_842_000,
    status: 'ready',
    chunkCount: 124,
    createdAt: new Date(Date.now() - 86_400_000 * 3).toISOString(),
  },
  {
    id: uid(),
    name: 'Q1 Engineering Roadmap.md',
    sizeBytes: 48_200,
    status: 'ready',
    chunkCount: 31,
    createdAt: new Date(Date.now() - 86_400_000).toISOString(),
  },
  {
    id: uid(),
    name: 'Security Policy.docx',
    sizeBytes: 264_000,
    status: 'processing',
    chunkCount: 0,
    createdAt: new Date().toISOString(),
  },
]

export function addDocument(file: File): RagDocument {
  const doc: RagDocument = {
    id: uid(),
    name: file.name,
    sizeBytes: file.size,
    status: 'processing',
    chunkCount: 0,
    createdAt: new Date().toISOString(),
  }
  documents.unshift(doc)
  // Simulate async ingestion: chunking + embedding finishes after a delay.
  setTimeout(() => {
    doc.status = 'ready'
    doc.chunkCount = Math.max(1, Math.round(file.size / 1500))
  }, 2500)
  return doc
}

export function removeDocument(id: string): void {
  const i = documents.findIndex((d) => d.id === id)
  if (i !== -1) documents.splice(i, 1)
}

/** Fabricate a RAG-style answer that cites a couple of ready documents. */
export function mockAnswer(question: string): {
  content: string
  citations: Citation[]
} {
  const ready = documents.filter((d) => d.status === 'ready')
  const cited = ready.slice(0, 2)
  const citations: Citation[] = cited.map((d) => ({
    documentId: d.id,
    documentName: d.name,
    snippet: `…relevant passage from ${d.name} matching "${question.slice(0, 40)}"…`,
  }))

  const content = ready.length
    ? `Based on your knowledge base, here's what I found regarding "${question.trim()}":\n\n` +
      `The retrieved context suggests a clear answer, drawn from ${cited
        .map((d) => `**${d.name}**`)
        .join(' and ')}. ` +
      `In a real deployment this response would be generated by the LLM from the retrieved chunks.`
    : `I couldn't find any ready documents in your knowledge base yet. ` +
      `Upload and process some documents first, then ask again.`

  return { content, citations }
}
